export const stories={
 'Miniscope V4':{
 kind:'imaging',label:'Neural imaging',headline:'Observe the brain.\nKeep behavior in view.',intro:'A neural imaging system for freely moving animal experiments, bringing the instrument and its recording workflow into one planned package.',question:'What happens in the brain as behavior unfolds?',context:'For laboratories studying reward seeking, learning and spontaneous movement, where neural recordings need to follow animals within the experimental environment.',steps:[
 ['Prepare','A coordinated starting point.','The planned package brings together imaging and recording equipment, supporting accessories and operating guidance.','Planned package','Imaging equipment · Recording equipment · Accessories · Guidance'],
 ['Record','Neural activity, recorded.','The system is designed to produce image recordings of neural activity in freely moving animals.','Intended output','Neural image recordings'],
 ['Investigate','Return to the research question.','Intended applications include reward seeking, learning and spontaneous movement experiments.','Research contexts','Reward seeking · Learning · Spontaneous movement']],
 difference:'Built around freely moving recordings.',comparison:'A standalone imaging device',approach:'The Blux prototype records the full field continuously at 120 Hz. At a quarter-sized field of view, in-house measurements reached 894 frames per second at the recorder. A coaxial cable handling unit is planned for future development, with the aim of supporting extended free-moving sessions alongside a depth camera; it is not part of the current prototype.',stage:'Bench prototype in development. Initial in-house imaging tests are underway.',cta:'Tell us about your recording experiment.',prompt:'Discuss the experimental task and the equipment your laboratory needs.'},
 'Multi-CAM Witness System':{
 kind:'arena',label:'Behavioral recording',headline:'Build the space\naround the experiment.',intro:'A modular, aluminum-framed observation platform for animal behavioral research, with dimensions, panels and camera arrangements adapted to the task.',question:'Does your recording setup fit your experiment?',context:'Behavioral studies call for different observation spaces. Multi-CAM starts with the physical setup and the views needed to record the experiment.',steps:[
 ['Frame','Start with the observation space.','Frame dimensions can be configured around the experimental setup.','Configuration','Frame dimensions'],
 ['Panels','Adapt the enclosure.','Panel materials form part of the configurable hardware package.','Configuration','Panel materials'],
 ['Cameras','Arrange the views.','Camera placement and hardware configuration are adapted to the experiment, producing video for behavioral observation and downstream processing.','Intended output','Behavioral video recordings']],
 difference:'A configurable observation platform.',comparison:'A fixed-dimension chamber',approach:'A modular frame with configurable dimensions, panel materials and camera arrangements.',stage:'Physical prototype. Configuration is discussed around the requirements of each experiment.',cta:'What does your observation space require?',prompt:'Share the arena dimensions, recording task and viewpoints you want to capture.'},
 'Experimental Digital Twin':{
 kind:'replay',label:'Experimental replay',headline:'Revisit the experiment.\nChange your perspective.',intro:'Turn experimental recordings into dynamic 3D representations for interactive review of animal movement.',question:'What could another viewpoint reveal?',context:'Prepare subject-focused visual data, inspect movement within the experimental setting and revisit events in 3D for qualitative review and discussion.',steps:[
 ['Select','Focus on the subject.','AI-assisted subject extraction and keypoint annotation help prepare recordings for review, starting with human review of the initial subject selection.','Output','Subject masks · Keypoint labeling'],
 ['Reconstruct','Bring movement into the scene.','Subject extraction and tracking connect experimental recordings to animated 3D representations.','Output','Animated 3D scenes'],
 ['Replay','Inspect from different viewpoints.','Replay movement within a digital experimental scene for qualitative inspection and discussion with colleagues.','Use','Interactive review']],
 difference:'From recording to interactive replay.',comparison:'Separate segmentation tools and 3D viewers',approach:'Recording processing, subject extraction and animated 3D visualization are connected within one workflow.',stage:'Working research prototype. Initial internal demonstrations completed.',cta:'Which recorded event would you revisit?',prompt:'Discuss your recordings and the movement you want to inspect in 3D.'},
 'Blux Research Agent':{
 kind:'workflow',label:'Research workflows',headline:'Keep the context.\nMove the research forward.',intro:'An AI research agent for experimental files, scientific tools and the work between raw data and a traceable result.',question:'How much work happens between your tools?',context:'Video-based biology and animal-behavior experiments produce files, metadata and intermediate results that researchers must repeatedly organize and pass between analysis tools.',steps:[
 ['Organize','Start with experimental context.','Organize experimental files and metadata around the experiment.','Inputs','Experimental files · Metadata'],
 ['Coordinate','Connect the processing steps.','Invoke processing tools according to the experiment, available data and workflow state.','Work','Data preparation · Tool coordination'],
 ['Trace','Keep track of what comes out.','Track processing outputs throughout the workflow, preserving context from raw experiment to final result.','Outputs','Processing results · Provenance']],
 difference:'An agent that works across the workflow.',comparison:'A generic question-answering assistant',approach:'Acts on experimental files, scientific tools, workflow state and processing outputs, rather than only answering questions.',stage:'Prototype. Built for data-intensive research workflows, particularly video-based biology and animal-behavior studies.',cta:'Where does your workflow slow down?',prompt:'Tell us about your files, processing tools and repetitive preparation steps.'}
};
